-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON t.typnamespace = n.oid WHERE t.typname = 'fulfillment_status_type' AND n.nspname = 'public') THEN
        CREATE TYPE public.fulfillment_status_type AS ENUM ('unfulfilled', 'partially_fulfilled', 'fulfilled', 'restocked');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON t.typnamespace = n.oid WHERE t.typname = 'payment_status_type' AND n.nspname = 'public') THEN
        CREATE TYPE public.payment_status_type AS ENUM ('pending', 'paid', 'refunded', 'partially_refunded', 'voided', 'failed');
    END IF;
END$$;

CREATE TABLE IF NOT EXISTS public.ab_assignments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  visitor_id uuid NOT NULL,
  test_id uuid NOT NULL,
  variant_id uuid NOT NULL,
  session_id text,
  assigned_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ab_assignments_pkey PRIMARY KEY (id),
  CONSTRAINT ab_assignments_test_id_fkey FOREIGN KEY (test_id) REFERENCES public.ab_tests(id),
  CONSTRAINT ab_assignments_variant_id_fkey FOREIGN KEY (variant_id) REFERENCES public.ab_variants(id)
);
CREATE TABLE IF NOT EXISTS public.ab_tests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  description text,
  status text NOT NULL DEFAULT 'draft'::text,
  start_date timestamp with time zone,
  end_date timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ab_tests_pkey PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS public.ab_variants (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  test_id uuid NOT NULL,
  name text NOT NULL,
  weight integer DEFAULT 50,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ab_variants_pkey PRIMARY KEY (id),
  CONSTRAINT ab_variants_test_id_fkey FOREIGN KEY (test_id) REFERENCES public.ab_tests(id)
);
CREATE TABLE IF NOT EXISTS public.addresses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  customer_id uuid,
  first_name text,
  last_name text,
  company text,
  address1 text,
  address2 text,
  city text,
  province text,
  country text,
  zip text,
  phone text,
  is_default boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT addresses_pkey PRIMARY KEY (id),
  CONSTRAINT addresses_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id)
);
CREATE TABLE IF NOT EXISTS public.analytics_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  session_id text NOT NULL,
  user_id uuid,
  event_name text NOT NULL,
  properties jsonb DEFAULT '{}'::jsonb,
  url text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  visitor_id uuid,
  CONSTRAINT analytics_events_pkey PRIMARY KEY (id),
  CONSTRAINT analytics_events_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.sessions(id),
  CONSTRAINT analytics_events_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE IF NOT EXISTS public.attribution_touchpoints (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  visitor_id uuid NOT NULL,
  session_id text,
  touchpoint_number integer,
  channel text,
  source text,
  medium text,
  campaign text,
  content text,
  term text,
  landing_page text,
  referrer text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT attribution_touchpoints_pkey PRIMARY KEY (id),
  CONSTRAINT attribution_touchpoints_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.sessions(id)
);
CREATE TABLE IF NOT EXISTS public.cart_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  session_id text,
  visitor_id uuid,
  event_type text NOT NULL,
  product_id text,
  sku text,
  product_name text,
  quantity integer,
  unit_price numeric,
  total_value numeric,
  cart_total numeric,
  cart_item_count integer,
  source_page text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT cart_events_pkey PRIMARY KEY (id),
  CONSTRAINT cart_events_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.sessions(id)
);
CREATE TABLE IF NOT EXISTS public.cart_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  product_id text NOT NULL,
  name text NOT NULL,
  price numeric NOT NULL,
  quantity integer NOT NULL DEFAULT 1,
  image text,
  subscription boolean DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  session_id text,
  sku text,
  visitor_id uuid,
  CONSTRAINT cart_items_pkey PRIMARY KEY (id),
  CONSTRAINT cart_items_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE IF NOT EXISTS public.checkout_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  session_id text,
  visitor_id uuid,
  checkout_token text,
  step text NOT NULL,
  step_number integer,
  cart_value numeric,
  item_count integer,
  shipping_method text,
  payment_method text,
  discount_code text,
  error_message text,
  time_on_step_ms integer,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT checkout_events_pkey PRIMARY KEY (id),
  CONSTRAINT checkout_events_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.sessions(id)
);
CREATE TABLE IF NOT EXISTS public.click_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  session_id text,
  visitor_id uuid,
  page_url text,
  element_id text,
  element_class text,
  element_tag text,
  element_text text,
  x_position integer,
  y_position integer,
  viewport_width integer,
  viewport_height integer,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT click_events_pkey PRIMARY KEY (id),
  CONSTRAINT click_events_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.sessions(id)
);
CREATE TABLE IF NOT EXISTS public.customer_feedback (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  customer_id uuid,
  order_id uuid,
  feedback_type text,
  score integer,
  comment text,
  tags text[],
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT customer_feedback_pkey PRIMARY KEY (id),
  CONSTRAINT customer_feedback_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT customer_feedback_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id)
);
CREATE TABLE IF NOT EXISTS public.customers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  auth_user_id uuid,
  email text UNIQUE,
  phone text,
  first_name text,
  last_name text,
  accepts_marketing boolean DEFAULT false,
  orders_count integer DEFAULT 0,
  total_spent numeric DEFAULT 0,
  last_order_id uuid,
  note text,
  tags text[],
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  first_order_date timestamp with time zone,
  last_order_date timestamp with time zone,
  average_order_value numeric DEFAULT 0,
  acquisition_source text,
  acquisition_campaign text,
  lifetime_discount_used numeric DEFAULT 0,
  lifetime_refunds numeric DEFAULT 0,
  subscription_status text,
  predicted_ltv numeric,
  churn_risk_score numeric,
  customer_segment text,
  CONSTRAINT customers_pkey PRIMARY KEY (id),
  CONSTRAINT customers_auth_user_id_fkey FOREIGN KEY (auth_user_id) REFERENCES auth.users(id)
);
CREATE TABLE IF NOT EXISTS public.discounts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  code text NOT NULL UNIQUE,
  type text NOT NULL,
  value numeric NOT NULL,
  starts_at timestamp with time zone DEFAULT now(),
  ends_at timestamp with time zone,
  usage_limit integer,
  usage_count integer DEFAULT 0,
  min_requirement_type text,
  min_requirement_value numeric,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT discounts_pkey PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS public.form_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  session_id text,
  visitor_id uuid,
  form_id text,
  form_name text,
  field_name text,
  event_type text,
  field_value_length integer,
  time_spent_ms integer,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT form_events_pkey PRIMARY KEY (id),
  CONSTRAINT form_events_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.sessions(id)
);
CREATE TABLE IF NOT EXISTS public.inventory_movements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  product_id uuid,
  sku text,
  movement_type text,
  quantity_change integer,
  quantity_before integer,
  quantity_after integer,
  reference_id uuid,
  reference_type text,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT inventory_movements_pkey PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS public.order_items (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  order_id uuid,
  product_id text,
  name text,
  quantity integer,
  price numeric,
  subscription boolean DEFAULT false,
  image text,
  cost_per_item numeric DEFAULT 0,
  sku text,
  product_uuid uuid,
  variant_title text,
  vendor text,
  properties jsonb,
  fulfillable_quantity integer,
  fulfillment_status fulfillment_status_type DEFAULT 'unfulfilled'::fulfillment_status_type,
  product_name text,
  CONSTRAINT order_items_pkey PRIMARY KEY (id),
  CONSTRAINT order_items_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id)
);
CREATE TABLE IF NOT EXISTS public.orders (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid,
  stripe_payment_intent_id text,
  amount numeric,
  status text DEFAULT 'pending'::text,
  shipping_details jsonb,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  session_id text,
  subtotal_price numeric DEFAULT 0,
  total_tax numeric DEFAULT 0,
  total_shipping numeric DEFAULT 0,
  total_discounts numeric DEFAULT 0,
  discount_code text,
  landing_site text,
  visitor_id uuid,
  net_sales numeric DEFAULT 0,
  order_number integer NOT NULL DEFAULT nextval('orders_order_number_seq'::regclass),
  customer_id uuid,
  financial_status payment_status_type DEFAULT 'pending'::payment_status_type,
  fulfillment_status fulfillment_status_type DEFAULT 'unfulfilled'::fulfillment_status_type,
  currency text DEFAULT 'USD'::text,
  cancel_reason text,
  cancelled_at timestamp with time zone,
  tags text[],
  note text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  processed_at timestamp with time zone,
  browser text,
  os text,
  ip_address text,
  checkout_duration_seconds integer,
  is_first_order boolean DEFAULT false,
  landing_page text,
  referrer text,
  total_amount numeric DEFAULT 0,
  tax_price numeric DEFAULT 0,
  shipping_price numeric DEFAULT 0,
  discount_amount numeric DEFAULT 0,
  tracking_number text,
  carrier text,
  shipped_at timestamp with time zone,
  CONSTRAINT orders_pkey PRIMARY KEY (id),
  CONSTRAINT orders_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT orders_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id)
);
CREATE TABLE IF NOT EXISTS public.page_views (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  session_id text,
  visitor_id uuid,
  url text NOT NULL,
  path text,
  title text,
  referrer text,
  referrer_host text,
  time_on_page integer,
  scroll_depth integer,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT page_views_pkey PRIMARY KEY (id),
  CONSTRAINT page_views_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.sessions(id)
);
CREATE TABLE IF NOT EXISTS public.product_views (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  session_id text,
  visitor_id uuid,
  product_id text,
  sku text,
  product_name text,
  variant_viewed text,
  price_shown numeric,
  source_page text,
  time_on_page integer,
  added_to_cart boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT product_views_pkey PRIMARY KEY (id),
  CONSTRAINT product_views_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.sessions(id)
);
CREATE TABLE IF NOT EXISTS public.products (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  sku text NOT NULL UNIQUE,
  description text,
  price numeric NOT NULL,
  compare_at_price numeric,
  currency text DEFAULT 'USD'::text,
  image_url text,
  category text,
  active boolean DEFAULT true,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT products_pkey PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid NOT NULL,
  updated_at timestamp with time zone,
  username text UNIQUE CHECK (char_length(username) >= 3),
  full_name text,
  avatar_url text,
  website text,
  role text DEFAULT 'customer'::text,
  email text,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE IF NOT EXISTS public.refunds (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id uuid,
  customer_id uuid,
  amount numeric NOT NULL,
  reason text,
  reason_category text,
  status text DEFAULT 'pending'::text,
  refund_method text,
  processed_at timestamp with time zone,
  processed_by uuid,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT refunds_pkey PRIMARY KEY (id),
  CONSTRAINT refunds_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id),
  CONSTRAINT refunds_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id)
);
CREATE TABLE IF NOT EXISTS public.search_queries (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  session_id text,
  visitor_id uuid,
  query text NOT NULL,
  results_count integer,
  clicked_result_position integer,
  clicked_product_id text,
  filters_applied jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT search_queries_pkey PRIMARY KEY (id),
  CONSTRAINT search_queries_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.sessions(id)
);
CREATE TABLE IF NOT EXISTS public.sessions (
  id text NOT NULL,
  user_id uuid,
  last_seen timestamp with time zone DEFAULT timezone('utc'::text, now()),
  user_agent text,
  path text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  converted_at timestamp with time zone,
  last_order_id uuid,
  ip_address text,
  country text,
  city text,
  device_type text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  utm_term text,
  utm_content text,
  browser text,
  visitor_id uuid,
  region text,
  landing_page text,
  exit_page text,
  pages_viewed integer DEFAULT 0,
  session_duration integer,
  bounce boolean DEFAULT false,
  is_new_visitor boolean DEFAULT true,
  referrer text,
  referrer_host text,
  screen_width integer,
  screen_height integer,
  timezone text,
  language text,
  CONSTRAINT sessions_pkey PRIMARY KEY (id),
  CONSTRAINT sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT sessions_last_order_id_fkey FOREIGN KEY (last_order_id) REFERENCES public.orders(id)
);
CREATE TABLE IF NOT EXISTS public.subscription_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  customer_id uuid,
  order_id uuid,
  event_type text NOT NULL,
  subscription_id text,
  product_sku text,
  interval_type text,
  mrr_change numeric,
  cancel_reason text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT subscription_events_pkey PRIMARY KEY (id),
  CONSTRAINT subscription_events_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT subscription_events_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id)
);
